import GlobalLayout from '@/ui/GlobalLayout'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Roi Crm',
  description: 'Generated by create next app',
  category: 'Personal',
  keywords: 'next.js, typescript, tailwind, react',
  icons: {
    icon: 'https://res.cloudinary.com/dfletli2x/image/upload/icons/reg/qrcode.svg',
    shortcut: 'https://res.cloudinary.com/dfletli2x/image/upload/icons/reg/qrcode.svg',
    apple: 'https://res.cloudinary.com/dfletli2x/image/upload/icons/reg/qrcode.svg',
  },
  openGraph: {
    type: 'website',
    title: 'Roi Crm',
    description: 'Generated by create next app',
    url: 'https://yourwebsite.com',
    siteName: 'Roi Crm',
    images: [
      {
        url: 'https://res.cloudinary.com/dfletli2x/image/upload/icons/reg/qrcode.svg',
        width: 1200,
        height: 630,
        alt: 'Roi Crm Icon',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Roi Crm',
    description: 'Generated by create next app',
    images: ['https://res.cloudinary.com/dfletli2x/image/upload/icons/reg/qrcode.svg'],
  },
}

export default async function RootLayout({ children }) {
  return (
    <GlobalLayout>
      <div className="grid desktop:grid-cols-2 w-screen bg-white place-items-center min-h-svh">
        <div className="mx-4">
          <h1 className="text-5xl mobile:text-3xl font-bold text-center mb-8">
            ברוכים הבאים ל <span className={gradTxt}>RoiCrm</span>
          </h1>
          {children}
        </div>
        <img src="auth_bg.jpg" alt="" className="w-full h-screen mobile:hidden" />
      </div>
    </GlobalLayout>
  )
}
// --experimental-https

const gradTxt =
  'bg-gradient-to-r from-blue-700 to-pink-700 inline-block text-transparent bg-clip-text font-black text-6xl mobile:text-4xl'
