import PopMsg from 'zvijude/pop'
import '@/ui/globals.css'
import { Metadata } from 'next'
import { getUser } from '@/auth/authFuncs'
import UserProvider from '@/utils/userCtx'
import { Assistant } from 'next/font/google'

const font = Assistant({ subsets: ['hebrew'], weight: ['400', '600', '700'], display: 'swap' })

export const metadata: Metadata = {
  title: 'Roi Crm',
  description: 'Generated by create next app',
  category: 'Personal',
  keywords: 'next.js, typescript, tailwind, react',
  icons: {
    icon: 'https://res.cloudinary.com/dfletli2x/image/upload/icons/reg/qrcode.svg',
    shortcut: 'https://res.cloudinary.com/dfletli2x/image/upload/icons/reg/qrcode.svg',
    apple: 'https://res.cloudinary.com/dfletli2x/image/upload/icons/reg/qrcode.svg',
  },
  openGraph: {
    type: 'website',
    title: 'Roi Crm',
    description: 'Generated by create next app',
    url: 'https://yourwebsite.com',
    siteName: 'Roi Crm',
    images: [
      {
        url: 'https://res.cloudinary.com/dfletli2x/image/upload/icons/reg/qrcode.svg',
        width: 1200,
        height: 630,
        alt: 'Roi Crm Icon',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Roi Crm',
    description: 'Generated by create next app',
    images: ['https://res.cloudinary.com/dfletli2x/image/upload/icons/reg/qrcode.svg'],
  },
}

export default async function GlobalLayout({ children }) {
  const user = await getUser()

  return (
    <html lang="he" dir="rtl">
      <body className={font.className}>
        <UserProvider data={user}>
          <PopMsg />
          {children}
        </UserProvider>
      </body>
    </html>
  )
}
