ALTER TABLE "MainTask"
ALTER COLUMN "updatedAt" SET DEFAULT now();

ALTER TABLE "Qr"
ALTER COLUMN "updatedAt" SET DEFAULT now();

ALTER TABLE "Task"
ALTER COLUMN "updatedAt" SET DEFAULT now();

ALTER TABLE "Prob"
ALTER COLUMN "updatedAt" SET DEFAULT now();

ALTER TABLE "Company"
ALTER COLUMN "updatedAt" SET DEFAULT now();

